export {
  CAMPUS_OPTIONS,
  DEPARTMENT_OPTIONS,
  DORMITORY_OPTIONS,
  GENDER_OPTIONS,
  GRADE_OPTIONS,
  MY_PROFILE_EDIT_DEFAULT_VALUES,
  MY_PROFILE_EDIT_FORM_ID,
  PROFILE_PLACEHOLDER,
  SELECT_TRIGGER_CLASS_NAME,
  WAVE_BACKGROUND_CLASS_NAME,
} from "@/features/mypage/constants/myProfileEditContent.constants";
