export {
  AGE_OPTIONS,
  DEPARTMENT_OPTIONS,
  MY_PROFILE_EDIT_DEFAULT_VALUES,
  MY_PROFILE_EDIT_FORM_ID,
  PROFILE_PLACEHOLDER,
  SELECT_TRIGGER_CLASS_NAME,
  WAVE_BACKGROUND_CLASS_NAME,
} from "@/features/mypage/constants/myProfileEditContent.constants";
